"""Copy original Figma PNG frames and latest narrative stills; retain provenance.

No cropping, AI reconstruction or upscaling. Source exports remain untouched.
"""
from pathlib import Path
import hashlib
import json
import re
import shutil
import sys
from PIL import Image

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'artifacts/DESIGN/figma-exports/MAX-game-screencast-2026-09-29_14-05-31'
OUT = ROOT / 'artifacts/max-game/public/assets/client-media'

def main():
    sys.stdout.reconfigure(encoding='utf-8')
    code = (ROOT/'artifacts/max-game/src/journey-media.mjs').read_text(encoding='utf-8')
    ids = set(re.findall(r'\b\d{5,6}\b', code))
    OUT.mkdir(parents=True, exist_ok=True)
    records = {}
    for metadata in SOURCE.rglob('screen.json'):
        screen = json.loads(metadata.read_text(encoding='utf-8-sig'))
        key = screen['id'].split(':')[-1]
        if key not in ids:
            continue
        source = metadata.parent/'screen.png'
        records[key] = copy(source, f'frame-{key}.png', screen['name'], node=screen['id'])
    absent = ids-set(records)
    if absent:
        raise RuntimeError(f'Figma nodes absent: {sorted(absent)}')
    stills = ROOT/'artifacts/max-game/design/digital-id-mascot-urban-stills-20260930'
    for source in sorted(stills.glob('*-0[12]-*.png')):
        records[source.stem] = copy(source, source.name, source.stem, kind='narrative-still')
    # Original customer screenshot shows delivery tracking, not order acceptance.
    source = Path('C:/Users/FUTURO~1/AppData/Local/Temp/codex-clipboard-69351ce6-1c3a-464e-8ea5-e89cb8444828.png')
    existing = OUT/'bot-delivery.png'
    if source.exists():
        records['bot-delivery'] = copy(source, existing.name, 'Бот: статус и изменение доставки', kind='client-attachment')
    elif existing.exists():
        previous = json.loads((OUT/'sources.json').read_text(encoding='utf-8'))
        records['bot-delivery'] = previous['bot-delivery']
    else:
        raise RuntimeError('Missing original delivery attachment')
    (OUT/'sources.json').write_text(json.dumps(records, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    assets = {key:{k:r[k] for k in ('src','label','width','height')} for key,r in records.items()}
    (ROOT/'artifacts/max-game/src/journey-media-assets.mjs').write_text('// Generated by prepare-client-media.py; original pixels preserved.\nexport const MEDIA_ASSETS='+json.dumps(assets, ensure_ascii=False, indent=2)+';\n', encoding='utf-8')
    print(f'Prepared {len(records)} original images, {sum((OUT/Path(r["src"]).name).stat().st_size for r in records.values())/1024**2:.1f} MiB')

def copy(source, filename, label, **extra):
    shutil.copyfile(source, OUT/filename)
    with Image.open(source) as image:
        width, height = image.size
    try:
        provenance = source.relative_to(ROOT).as_posix()
    except ValueError:
        provenance = str(source)
    return dict(src='./assets/client-media/'+filename, label=label, width=width, height=height,
                source=provenance, sha256=hashlib.sha256(source.read_bytes()).hexdigest(), **extra)

if __name__ == '__main__':
    main()
