import {assets} from './assets.mjs';
import {DescriptorView,warmDescriptor,warmAssets} from './descriptor-view.mjs';
import {createSiteSession,SITE_SHARED_KEY} from './site-session.mjs';
import {createBrowserPersistence} from './browser-persistence.mjs';
import {missions as visualMissions,Hold,SCENE,WALL_SCENE,WALL_GAME,WALL_MOVE,WALL_INPUT,WALL_ROUTE,SITE_ROUTE_MOTION,ROUTE_LINK_STAGGER,PHONE_FIBER_COUNT,visibleRouteLinkCount,wallLinePositions,clampNodeToField,planPhoneInsertion,translatePhonePlan,routeIdleOffset,clampPhonePose,phoneFiberPorts,phoneFiberReveal,fitScene} from './model.mjs?v=client-review56';
import {IconMotion,MotionValue,MOTION} from './original/journey-motion.mjs';
import {JOURNEY_LINK_STYLE,tileEdgeCurve,sampleTileEdgeCurve} from './original/journey-links.mjs';
import {REVEAL_TIMING,REVEAL_MOTION,revealTracePresence,revealBurstDuration,revealLaunchPoint,revealNodeTarget} from './site-reveal-motion.mjs';
import {applyGlowTiming,clearGlowTiming,setGlowPaused} from './rim-glow.mjs?v=phase50';
const app=document.querySelector('#app'),notice=document.querySelector('#notice'),hold=new Hold();
const wallMode=new URLSearchParams(location.search).get('layout')==='wall';
const scene=wallMode?WALL_SCENE:SCENE;
const routeCenterX=wallMode?WALL_ROUTE.centerX:SCENE.width/2;
const routeCenterY=wallMode?WALL_ROUTE.centerY:360;
const motionWidth=SCENE.width;
if(wallMode){
 app.classList.add('wall-scene');
 app.style.setProperty('--game-left',`${WALL_GAME.left}px`);
 app.style.setProperty('--game-top',`${WALL_GAME.top}px`);
 app.style.setProperty('--game-width',`${WALL_GAME.right-WALL_GAME.left}px`);
 app.style.setProperty('--game-height',`${WALL_GAME.bottom-WALL_GAME.top}px`);
 app.style.setProperty('--input-left',`${WALL_INPUT.left}px`);
 app.style.setProperty('--input-top',`${WALL_INPUT.top}px`);
 app.style.setProperty('--input-width',`${WALL_INPUT.right-WALL_INPUT.left}px`);
 app.style.setProperty('--input-height',`${WALL_INPUT.bottom-WALL_INPUT.top}px`);
 app.style.setProperty('--route-center-x',`${WALL_ROUTE.centerX}px`);
 app.style.setProperty('--route-center-y',`${WALL_ROUTE.centerY}px`);
}
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let mission=null,phase='menu',phaseElapsed=0,idleClock=0,lastFrame=performance.now(),sessionAt=0,noticeUntil=0,step=0,nodeMotions=[],linkEntries=[],linkElapsed=0,linkInstant=false,manualPositions={},dragGesture=null,phoneGesture=null,phoneShift={x:0,y:0},suppressClick=null,phoneMotion=null,phonePlan=null,phoneSide=null,phoneFiberElapsed=0;
let channelView=null,reviewView=null,activeDeviceWidth=370,session=null,catalog=null,missions=[],renderedTaskId=null,renderedScreenId=null,restoringResult=false;
function disposeChannel(){channelView?.dispose();channelView=null;reviewView?.dispose();reviewView=null;}
const brandbookContour=()=>'<div class="animated-card__glow-outer svelte-9yl9sx" aria-hidden="true"><div class="animated-card__glow-inner svelte-9yl9sx"></div><div class="animated-card__glow-track svelte-9yl9sx"><div class="animated-card__glow svelte-9yl9sx"></div></div></div>';
const fiberGradient=id=>`<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stop-color="#9500ff"/><stop offset="52%" stop-color="#6e1aff"/><stop offset="100%" stop-color="#6e1aff" stop-opacity=".55"/></linearGradient>`;
function aimFiberGradient(gradient,start,end){if(!gradient)return;const finish=Math.hypot(end.x-start.x,end.y-start.y)<1?{x:start.x+1,y:start.y}:end;gradient.setAttribute('x1',start.x.toFixed(1));gradient.setAttribute('y1',start.y.toFixed(1));gradient.setAttribute('x2',finish.x.toFixed(1));gradient.setAttribute('y2',finish.y.toFixed(1));}
const palmIcon=()=>'<svg class="palm-icon" viewBox="0 0 64 64" aria-hidden="true"><path d="M16 33V17c0-6 7-6 7 0v14-21c0-6 7-6 7 0v20-24c0-6 7-6 7 0v24-19c0-6 7-6 7 0v23l4-8c3-6 10-2 7 4l-9 22c-3 7-8 11-16 11-8 0-13-4-17-10L5 39c-4-6 2-10 6-6l5 5Z"/></svg>';
const wallFrame=()=>wallMode?'<div class="game-frame" aria-hidden="true"><span>ИГРОВАЯ ЗОНА · 1760 × 1024</span></div><div class="reach-band" aria-hidden="true"><span>ЗОНА ДОСЯГАЕМОСТИ · 1,0–1,8 М</span></div><div class="visual-zone-label" aria-hidden="true">ВИЗУАЛЬНАЯ ЗОНА · ПРАВАЯ СТЕНА 4096 × 1280</div>':'';
function resize(){const p=fitScene(innerWidth,innerHeight,scene);app.style.transform=`translate(${p.x}px,${p.y}px) scale(${p.scale})`;}
window.addEventListener('resize',resize);resize();
const missing=()=>'<span class="missing" role="img" aria-label="Нет ассета">?</span>';
const art=key=>key?`<img src="${assets[key]}" alt="" draggable="false">`:missing();
const header=()=>`<header><button class="timer" id="menu" aria-label="Вернуться к миссиям">3:00</button><img class="brand" src="${assets.logo}" alt="MAX"><button class="restart" id="restart" aria-label="Начать миссию заново">↻</button></header>`;
function tell(text){notice.textContent=text;noticeUntil=performance.now()+2600;notice.classList.add('visible');}
function persist(){if(!session?.snapshot)return;const nodes=session.snapshot.view.nodes,positions={...session.snapshot.layouts.positions};for(const [index,position] of Object.entries(manualPositions)){const id=nodes[Number(index)]?.nodeId;if(id)positions[id]=position;}session.layout(positions);}
async function menu(){const result=await session.command('RETURN_MENU');if(result?.reply.ok)renderMenu();}
function renderMenu(){clearGlowTiming();hold.cancel();disposeChannel();abortPhoneDrag();phase='menu';mission=null;nodeMotions=[];linkEntries=[];phoneMotion=null;phonePlan=null;phoneSide=null;dragGesture=null;phoneShift={x:0,y:0};app.innerHTML=wallFrame()+`<header><img class="brand" src="${assets.logo}" alt="MAX"><button class="restart" id="reset" aria-label="Сбросить весь прогресс">↻</button></header><main class="menu"><h1>Откройте возможности MAX</h1><p class="intro">Выберите миссию. Красный вопросительный знак обозначает отсутствующий материал.</p><div class="missions">${missions.map(m=>`<button class="mission-card animated-card animated-card--glow svelte-9yl9sx" data-mission="${m.id}">${brandbookContour()}<span class="card-art">${art(m.art)}</span><span class="card-copy"><span class="tag">${m.test?'ТЕСТОВАЯ МИССИЯ':'МИССИЯ'}</span><strong>${m.title}</strong><span class="coverage">${m.hasGaps?'Есть недостающие материалы':'Материалы доступны'}</span></span></button>`).join('')}</div></main>`;
 app.querySelector('#reset').onclick=async()=>{const result=await session.command('RESET_PROGRESS');if(result?.reply.ok){refreshMissions();renderMenu();}};
 app.querySelectorAll('[data-mission]').forEach(b=>{applyGlowTiming(b,`mission:${b.dataset.mission}`);b.onclick=()=>start(b.dataset.mission);});
}
async function start(id){const result=await session.command('SELECT_MISSION',{missionId:id});if(result?.reply.ok)mountMission(result.snapshot);}
function mountMission(snapshot){clearGlowTiming();hold.cancel();disposeChannel();abortPhoneDrag();refreshMissions();mission=missions.find(m=>m.id===snapshot.state.missionId);const scanned=snapshot.state.scanned;restoringResult=snapshot.state.status==='result';step=currentStep(snapshot);preload();sessionAt=performance.now();lastFrame=sessionAt;phaseElapsed=0;idleClock=0;linkElapsed=0;linkEntries=[];nodeMotions=[];phoneMotion=null;phonePlan=null;phoneSide=null;phoneShift={x:0,y:0};manualPositions={};snapshot.view.nodes.forEach((node,i)=>{if(snapshot.layouts.positions[node.nodeId])manualPositions[i]=snapshot.layouts.positions[node.nodeId];});dragGesture=null;phase=scanned?'ready':'palm';
 app.innerHTML=header()+`<main class="play">${wallFrame()}<div class="palm-wrap"><button class="palm animated-card svelte-9yl9sx" id="palm" aria-label="Удерживайте 0,8 секунды">${brandbookContour()}${palmIcon()}</button><h1>Приложи ладонь,<br>чтобы открыть возможности</h1><p>Удерживай 0,8 секунды</p></div><div class="route" hidden></div><div class="task" hidden></div></main>`;
 document.querySelector('#menu').onclick=menu;document.querySelector('#restart').onclick=async()=>{const result=await session.command('RESTART_MISSION');if(result?.reply.ok)mountMission(result.snapshot);};
 const palm=document.querySelector('#palm');
 applyGlowTiming(palm,`palm:${mission.id}`);
 palm.onpointerdown=e=>{if(phase!=='palm'||(e.pointerType==='mouse'&&e.button!==0))return;if(hold.down(e.pointerId,performance.now())){palm.setPointerCapture(e.pointerId);palm.classList.add('holding');session.contact(`p${e.pointerId}`,'down',true);preload();}};
 palm.onpointermove=e=>{const r=palm.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)cancel(e.pointerId);};
 palm.onpointerup=palm.onpointercancel=palm.onlostpointercapture=e=>cancel(e.pointerId);
 palm.onkeydown=e=>{if((e.code==='Space'||e.code==='Enter')&&!e.repeat){e.preventDefault();if(phase==='palm'&&hold.down('keyboard',performance.now())){palm.classList.add('holding');session.contact('keyboard','down',true);preload();}}};
 palm.onkeyup=e=>{if(e.code==='Space'||e.code==='Enter')cancel('keyboard');};palm.onblur=()=>cancel('keyboard');
 if(scanned){drawRoute();document.querySelector('.palm-wrap').hidden=true;const route=document.querySelector('.route');route.classList.add('linear','labels-visible');const current=route.querySelector(`[data-step="${step}"] strong`);if(current)current.textContent+=' · Продолжить';placeLineInstant();drawLinks(true);if(step>=mission.steps.length)showFinal();}
}
function cancel(id){const wasOwner=hold.owner===id;hold.release(id);if(wasOwner){session?.contact(id==='keyboard'?'keyboard':`p${id}`,'cancel',false);document.querySelector('.palm')?.classList.remove('holding');}}
function preload(){if(!session?.snapshot)return;warmDescriptor(session.snapshot.view);const taskId=session.snapshot.state.taskId??catalog.missions[session.snapshot.state.missionId]?.taskIds[0],task=catalog?.tasks[taskId];if(task)warmAssets(Object.values(task.screens).map(screen=>catalog.assets[screen.assetId]));const ids=catalog.missions[session.snapshot.state.missionId]?.taskIds??[],next=catalog.tasks[ids[ids.indexOf(taskId)+1]];if(next)warmAssets(Object.values(next.screens).slice(0,2).map(screen=>catalog.assets[screen.assetId]));}
function drawRoute(){const route=document.querySelector('.route');route.hidden=false;route.classList.add('original-motion');const nodes=['MAX',...mission.steps],style=JOURNEY_LINK_STYLE;const nodeArt={'blogger.channel':'channel','blogger.comments':'comments','blogger.statistics':'statistics','digital-id.create-id':'id','business.channel':'businessChannel','business.bot':'businessBot','business.store':'businessStore'};const visuals=['logo',...catalog.missions[mission.id].taskIds.map(id=>nodeArt[id]??null)];
 route.innerHTML=`<svg class="route-links original-fibers" viewBox="0 0 ${scene.width} ${wallMode?scene.height:800}" aria-hidden="true"><defs>${nodes.slice(1).map((_,i)=>fiberGradient(`route-violet-${i}`)).join('')}${Array.from({length:PHONE_FIBER_COUNT},(_,i)=>fiberGradient(`phone-violet-${i}`)).join('')}</defs>${nodes.slice(1).map((_,i)=>`<g class="route-link">${Array.from({length:style.strandCount},()=>`<path class="route-strand" stroke="url(#route-violet-${i})" pathLength="1"/>`).join('')}${Array.from({length:style.particleCount},()=>'<circle class="route-particle" r="2.4"/>').join('')}</g>`).join('')}<g class="phone-fibers">${Array.from({length:PHONE_FIBER_COUNT},(_,i)=>`<path stroke="url(#phone-violet-${i})" pathLength="1"/>`).join('')}</g></svg>`+nodes.map((title,i)=>{const spacing=Math.min(300,Math.max(180,(SCENE.width-260)/Math.max(1,nodes.length-1))),lineX=wallMode?wallLinePositions(nodes.length)[i]-routeCenterX:(i-(nodes.length-1)/2)*spacing;return `<button class="node animated-card animated-card--glow svelte-9yl9sx ${i===step+1?'current':''}" data-step="${i-1}" style="--line-x:${lineX}px">${brandbookContour()}<span class="node-art">${art(visuals[i])}</span><strong>${title}</strong></button>`;}).join('');
 for(const [i,element] of [...route.querySelectorAll('.node')].entries()){applyGlowTiming(element,`route:${mission.id}:${i}`);const captionHeight=element.querySelector('strong').offsetHeight;element.style.setProperty('--caption-lift',`${Math.max(36,captionHeight-27)}px`);}
 nodeMotions=[...route.querySelectorAll('.node')].map((element,i)=>{const p=revealLaunchPoint(i,nodes.length,motionWidth),motion=new IconMotion({x:p.worldX-motionWidth/2,y:p.worldY,size:240,radius:32,phase:i}),lineX=Number.parseFloat(element.style.getPropertyValue('--line-x')),saved=manualPositions[i],field=wallMode?WALL_MOVE:{left:0,right:SCENE.width,top:0,bottom:800},base=saved?clampNodeToField(saved.x,saved.y,field):{x:routeCenterX+lineX,y:routeCenterY};motion.alpha.value=0;return {element,motion,idle:new MotionValue(0),lineX,baseX:base.x-routeCenterX,baseY:base.y-routeCenterY,dragging:false};});
 route.querySelectorAll('button').forEach((b,i)=>{if(wallMode)installDrag(b,i);b.onclick=()=>{if(suppressClick?.element===b&&performance.now()<suppressClick.until){suppressClick=null;return;}if(['ready','task'].includes(phase)&&Number(b.dataset.step)===step)openTask();else if(Number(b.dataset.step)>step)tell('Откроется после текущего задания.');else tell('MAX — начало выбранной миссии.');};});
}
function installDrag(element,index){
 element.onpointerdown=e=>{if(!['ready','inserting','task'].includes(phase)||dragGesture||phoneGesture||(e.pointerType==='mouse'&&e.button!==0))return;const node=nodeMotions[index];dragGesture={id:e.pointerId,index,startX:e.clientX,startY:e.clientY,baseX:node.motion.x.value-phoneShift.x,baseY:node.motion.y.value,previousX:node.baseX,previousY:node.baseY,moved:false};node.motion.press();element.classList.add('pressed');element.setPointerCapture(e.pointerId);};
 element.onpointermove=e=>{const g=dragGesture;if(!g||g.id!==e.pointerId||g.index!==index)return;const scale=app.getBoundingClientRect().width/scene.width,dx=(e.clientX-g.startX)/scale,dy=(e.clientY-g.startY)/scale;if(!g.moved&&Math.hypot(e.clientX-g.startX,e.clientY-g.startY)<7)return;const node=nodeMotions[index];if(!g.moved){g.moved=true;node.dragTouched=true;}e.preventDefault();const p=clampNodeToField(routeCenterX+g.baseX+phoneShift.x+dx,routeCenterY+g.baseY+dy,WALL_MOVE);node.dragging=true;node.baseX=p.x-routeCenterX-phoneShift.x;node.baseY=p.y-routeCenterY;element.classList.add('dragging');};
 const end=(e,cancelled=false)=>{const g=dragGesture;if(!g||g.id!==e.pointerId||g.index!==index)return;dragGesture=null;const node=nodeMotions[index];if(element.hasPointerCapture(e.pointerId))element.releasePointerCapture(e.pointerId);element.classList.remove('dragging','pressed');node.dragging=false;if(!g.moved||cancelled){node.baseX=g.previousX;node.baseY=g.previousY;}else{manualPositions[index]={x:routeCenterX+node.baseX,y:routeCenterY+node.baseY};persist();suppressClick={element,until:performance.now()+500};}if(g.moved)e.preventDefault();};
 element.onpointerup=e=>end(e);element.onpointercancel=e=>end(e,true);element.onlostpointercapture=e=>end(e,true);
}
function abortDrag(){if(!dragGesture)return;const g=dragGesture;dragGesture=null;const node=nodeMotions[g.index];if(!node)return;node.baseX=g.previousX;node.baseY=g.previousY;node.dragging=false;node.element.classList.remove('dragging','pressed');}
function installPhoneDrag(device){
 device.onpointerdown=e=>{if(phase!=='task'||dragGesture||phoneGesture||phoneMotion?.alpha.value<.85||(e.pointerType==='mouse'&&e.button!==0)||e.target.closest('button,a,input,textarea,select'))return;phoneGesture={id:e.pointerId,startX:e.clientX,startY:e.clientY,startLeft:phoneMotion.x.value,startCenterY:phoneMotion.y.value,planLeft:phonePlan.left-phoneShift.x,previous:{...phoneShift},moved:false};device.setPointerCapture(e.pointerId);};
 device.onpointermove=e=>{const g=phoneGesture;if(!g||g.id!==e.pointerId)return;const scale=app.getBoundingClientRect().width/scene.width,dx=(e.clientX-g.startX)/scale,dy=(e.clientY-g.startY)/scale;if(!g.moved&&Math.hypot(e.clientX-g.startX,e.clientY-g.startY)<7)return;g.moved=true;e.preventDefault();const pose=clampPhonePose(g.startLeft+dx,g.startCenterY+dy,device.offsetWidth,device.offsetHeight,scene);phoneShift={x:pose.left-g.planLeft,y:pose.centerY-scene.height/2};device.classList.add('dragging');};
 const end=(e,cancelled=false)=>{const g=phoneGesture;if(!g||g.id!==e.pointerId)return;phoneGesture=null;if(device.hasPointerCapture(e.pointerId))device.releasePointerCapture(e.pointerId);device.classList.remove('dragging');if(cancelled)phoneShift=g.previous;else if(g.moved){persist();e.preventDefault();}};
 device.onpointerup=e=>end(e);device.onpointercancel=e=>end(e,true);device.onlostpointercapture=e=>end(e,true);
}
function abortPhoneDrag(){if(!phoneGesture)return;const g=phoneGesture;phoneGesture=null;phoneShift=g.previous;document.querySelector('.task .device')?.classList.remove('dragging');}
function placeLineInstant(){for(const {element,motion,baseX,baseY} of nodeMotions){const x=baseX+phoneShift.x,y=baseY;motion.x.value=x;motion.y.value=y;motion.x.velocity=0;motion.y.velocity=0;motion.alpha.value=1;element.style.transform=`translate(${x}px,${y}px)`;element.style.opacity='1';}}
function updateNodes(dt){
 const count=nodeMotions.length;if(!count)return;
 const settledPhase=['ready','inserting','task','result','closing','finished'].includes(phase),inserting=wallMode&&['inserting','task','result'].includes(phase);
 const manualIndices=Object.keys(manualPositions).map(Number);
 if(dragGesture?.moved)manualIndices.push(dragGesture.index);
 phonePlan=inserting?translatePhonePlan(planPhoneInsertion(nodeMotions.map(n=>({x:routeCenterX+n.baseX,y:routeCenterY+n.baseY})),step+1,WALL_GAME,activeDeviceWidth,{manualIndices,side:phoneSide}),phoneShift):null;
 for(let i=0;i<count;i++){
  const node=nodeMotions[i],{element,motion,lineX}=node,planned=phonePlan?.positions[i];
  const idleActive=wallMode&&['ready','task'].includes(phase)&&!dragGesture?.moved&&!phoneGesture?.moved&&!reduced.matches;
  node.idle.step(idleActive?1:0,dt,SITE_ROUTE_MOTION.idleOmega,reduced.matches);
  const idle=routeIdleOffset(idleClock,i);
  const target=settledPhase?{x:(planned?planned.x-routeCenterX:node.baseX+phoneShift.x)+idle.x*node.idle.value,y:(planned?planned.y-routeCenterY:node.baseY)+idle.y*node.idle.value,presence:1}:revealNodeTarget(phase,phaseElapsed,i,count,lineX,motionWidth);
  motion.step(dt,{x:settledPhase?target.x:target.worldX-motionWidth/2,y:settledPhase?target.y:target.worldY,size:240,radius:32,present:target.presence>0,dragging:node.dragging,expanded:!node.dragging,labelVisible:false,movementOmega:phoneGesture?.moved?SITE_ROUTE_MOTION.phoneFollowOmega:phase==='inserting'?REVEAL_MOTION.fieldOmega:settledPhase?MOTION.route:REVEAL_MOTION.fieldOmega,reduced:reduced.matches,time:idleClock});
  if(wallMode&&settledPhase&&node.dragTouched&&!phonePlan){const scale=motion.size.value/240,p=clampNodeToField(routeCenterX+motion.x.value,routeCenterY+motion.y.value,WALL_MOVE,motion.size.value,230*scale);if(p.x!==routeCenterX+motion.x.value){motion.x.value=p.x-routeCenterX;motion.x.velocity=0;}if(p.y!==routeCenterY+motion.y.value){motion.y.value=p.y-routeCenterY;motion.y.velocity=0;}}
  element.style.transform=`translate(${motion.x.value}px,${motion.y.value}px) scale(${motion.size.value/240})`;element.style.opacity=String(target.presence*motion.alpha.value);
 }
}
function insertionSettled(){return !dragGesture&&phonePlan&&nodeMotions.every((node,i)=>node.motion.x.at(phonePlan.positions[i].x-routeCenterX,3,25)&&node.motion.y.at(phonePlan.positions[i].y-routeCenterY,3,25));}
function updatePhone(dt){if(!wallMode||!phoneMotion||!phonePlan)return;const task=document.querySelector('.task'),device=task?.querySelector('.device');if(!device)return;if(['task','result'].includes(phase)){const omega=phoneGesture?.moved?MOTION.drag:REVEAL_MOTION.fieldOmega;phoneMotion.x.step(phonePlan.left,dt,omega,reduced.matches);phoneMotion.y.step(scene.height/2+phoneShift.y,dt,omega,reduced.matches);}phoneMotion.alpha.step(['task','result'].includes(phase)?1:0,dt,9,reduced.matches);device.style.left=`${phoneMotion.x.value}px`;device.style.top=`${phoneMotion.y.value}px`;device.style.opacity=String(phoneMotion.alpha.value);const icon=nodeBox(nodeMotions[step+1]),aside=task.querySelector('aside');if(aside){const width=activeDeviceWidth>370?460:600,afterDevice=phoneMotion.x.value+device.offsetWidth+35,afterIcon=icon.x+icon.w+35;aside.style.left=`${Math.max(0,Math.min(scene.width-width-20,phoneSide==='left'?Math.max(afterDevice,afterIcon):afterDevice))}px`;aside.style.opacity=String(phoneMotion.alpha.value);}const group=document.querySelector('.phone-fibers');if(!group)return;const height=device.offsetHeight,box={x:phoneMotion.x.value,y:phoneMotion.y.value-height/2,w:device.offsetWidth,h:height};const ports=phoneFiberPorts(icon,box,phonePlan.side);group.style.opacity=String(phoneMotion.alpha.value);[...group.querySelectorAll('path')].forEach((path,i)=>{const {start,end}=ports[i],bend=Math.max(35,Math.abs(end.x-start.x)*.45),sign=phonePlan.side==='right'?1:-1;aimFiberGradient(group.ownerSVGElement.querySelector(`#phone-violet-${i}`),start,end);path.setAttribute('d',`M${start.x.toFixed(1)} ${start.y.toFixed(1)} C${(start.x+sign*bend).toFixed(1)} ${start.y.toFixed(1)},${(end.x-sign*bend).toFixed(1)} ${end.y.toFixed(1)},${end.x.toFixed(1)} ${end.y.toFixed(1)}`);path.style.strokeDashoffset=String(1-phoneFiberReveal(phoneFiberElapsed,i,reduced.matches));});}
function nodesSettled(){return nodeMotions.every(({motion,lineX},i)=>{const goal=phase==='reveal'?revealNodeTarget('reveal',revealBurstDuration(nodeMotions.length),i,nodeMotions.length,lineX,motionWidth):revealNodeTarget('line',0,i,nodeMotions.length,lineX,motionWidth);return motion.x.at(goal.worldX-motionWidth/2,1.5,5)&&motion.y.at(goal.worldY,1.5,5);});}
const nodeBox=({motion})=>{const scale=motion.size.value/240,w=240*scale,h=230*scale;return {x:routeCenterX+motion.x.value-w/2,y:routeCenterY+motion.y.value-h/2,w,h};};
function drawLinks(instant=false){const route=document.querySelector('.route'),svg=route?.querySelector('.route-links');if(!svg)return;const boxes=nodeMotions.map(nodeBox),groups=[...svg.querySelectorAll('.route-link')],visibleCount=visibleRouteLinkCount(step,groups.length);groups.forEach((group,i)=>{group.style.opacity=i<visibleCount?'':'0';});linkEntries=groups.slice(0,visibleCount).map((group,i)=>{const curve=tileEdgeCurve(boxes[i],boxes[i+1]),samples=Array.from({length:JOURNEY_LINK_STYLE.segmentCount+1},(_,j)=>{const t=j/JOURNEY_LINK_STYLE.segmentCount;return {p:point(curve,t),n:normal(curve,t)};});return {group,gradient:svg.querySelector(`#route-violet-${i}`),curve,samples,paths:[...group.querySelectorAll('.route-strand')],particles:[...group.querySelectorAll('.route-particle')],offset:i*.23};});linkElapsed=0;linkInstant=instant;svg.classList.add('connected');updateLinks();}
const point=(curve,t)=>sampleTileEdgeCurve(curve,Math.max(0,Math.min(1,t)));const normal=(curve,t)=>{const a=point(curve,t-.002),b=point(curve,t+.002),dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy)||1;return {x:-dy/length,y:dx/length};};
function updateLinks(){const style=JOURNEY_LINK_STYLE,unit=560,center=(style.strandCount-1)*.5;for(const [edgeIndex,entry] of linkEntries.entries()){entry.group.style.opacity=phonePlan&&edgeIndex===(phonePlan.side==='right'?step+1:step)?'0':'';entry.curve=tileEdgeCurve(nodeBox(nodeMotions[edgeIndex]),nodeBox(nodeMotions[edgeIndex+1]),entry.curve);aimFiberGradient(entry.gradient,point(entry.curve,0),point(entry.curve,1));entry.samples=Array.from({length:style.segmentCount+1},(_,j)=>{const t=j/style.segmentCount;return {p:point(entry.curve,t),n:normal(entry.curve,t)};});const progress=linkInstant?1:revealTracePresence((linkElapsed-edgeIndex*ROUTE_LINK_STAGGER)/REVEAL_TIMING.trace);for(let laneIndex=0;laneIndex<style.strandCount;laneIndex++){const lane=(laneIndex-center)*style.strandSpacing,phase=laneIndex*.82+entry.offset*Math.PI*2;let d='';for(let sample=0;sample<=style.segmentCount;sample++){const t=sample/style.segmentCount,{p,n}=entry.samples[sample],wave=t*style.waveFrequency*Math.PI*2-linkElapsed*3.2+phase,lateral=(lane+Math.sin(wave)*style.waveAmplitude)*Math.sin(Math.PI*t)*unit;d+=`${sample?'L':'M'}${(p.x+n.x*lateral).toFixed(1)} ${(p.y+n.y*lateral).toFixed(1)}`;}const path=entry.paths[laneIndex];path.setAttribute('d',d);path.style.strokeDashoffset=String(1-progress);}
 for(let i=0;i<style.particleCount;i++){const t=(linkElapsed*style.flowSpeed+i/style.particleCount+entry.offset)%1,p=point(entry.curve,t),n=normal(entry.curve,t),lane=((i%style.strandCount)-center)*style.strandSpacing,wave=Math.sin(t*style.waveFrequency*Math.PI*2-linkElapsed*3.2+i)*style.waveAmplitude,lateral=(lane+wave)*Math.sin(Math.PI*t)*unit,circle=entry.particles[i];circle.setAttribute('cx',(p.x+n.x*lateral).toFixed(1));circle.setAttribute('cy',(p.y+n.y*lateral).toFixed(1));circle.style.opacity=t<=progress?String(.45+.45*Math.sin(linkElapsed*4.8+i*2.39996)**2):'0';}
 }}
function reveal(){cancel(hold.owner);phase='reveal';phaseElapsed=0;drawRoute();document.querySelector('.palm-wrap').classList.add('leaving');}
function finishTask(outcome){
 abortPhoneDrag();disposeChannel();phase='result';phaseElapsed=0;
 const task=document.querySelector('.task'),body=task.querySelector('.device-content'),aside=task.querySelector('aside');
 body.innerHTML=`<div class="review-result"><strong>${outcome==='skip'?'Материал пока недоступен':'Задание выполнено'}</strong><p>${outcome==='skip'?'Этот шаг не засчитан. Переходим дальше.':'Открываем следующую возможность MAX.'}</p></div>`;
 aside.replaceChildren();const note=document.createElement('p');note.textContent=outcome==='skip'?'Отсутствующий клиентский экран не считается выполненным заданием.':'Результат сохранён.';aside.append(note);
}
function showFinal(){
 disposeChannel();phase='finished';document.querySelector('.route')?.classList.remove('with-task');
 const task=document.querySelector('.task');task.hidden=false;task.classList.add('review-final-task');
 const snapshot=session.snapshot,result=snapshot.view.result,progress=snapshot.state.progress[mission.id],missed=progress.skipped.length,title=result?.title??(missed?'Маршрут просмотрен':'Миссия выполнена');
 task.innerHTML='<div class="review-final"><h2></h2><p></p><img alt="QR официального сайта MAX"><button class="primary" type="button">К миссиям</button></div>';task.querySelector('h2').textContent=title;task.querySelector('p').textContent=result?.text??(missed?`Выполнено ${progress.completed.length}; пропущено ${missed} из-за отсутствующих клиентских материалов.`:'Все задания миссии выполнены.');task.querySelector('img').src=`../${snapshot.view.qr?.asset?.path??'assets/presentation/max-site-qr.png'}`;
 task.querySelector('button').onclick=menu;
}
function openTask(){
 if(phase!=='ready')return;
 const snapshot=session.snapshot,taskId=snapshot.state.taskId;if(['completed','incomplete'].includes(snapshot.state.status)){showFinal();return;}if(snapshot.state.status!=='task')return;step=currentStep(snapshot);renderedTaskId=taskId;renderedScreenId=snapshot.state.screenId;preload();
 disposeChannel();phase=wallMode?'inserting':'task';phoneFiberElapsed=0;
 const task=document.querySelector('.task');task.classList.remove('review-final-task');task.style.opacity='1';task.hidden=false;
 document.querySelector('.route').classList.add('with-task');
 const hasChannel=taskId==='blogger.channel',isPc=snapshot.view.device?.kind==='pc';activeDeviceWidth=isPc?(wallMode?520:650):370;
 task.innerHTML=`<div class="device ${hasChannel?'channel-device':isPc?'review-pc':'review-phone'}"><div class="device-content"></div></div><aside></aside>`;
 if(wallMode){const plan=planPhoneInsertion(nodeMotions.map(n=>({x:routeCenterX+n.baseX,y:routeCenterY+n.baseY})),step+1,WALL_GAME,activeDeviceWidth);phoneSide=plan.side;phoneMotion??={x:new MotionValue(plan.left+phoneShift.x+(plan.side==='right'?90:-90)),y:new MotionValue(scene.height/2+phoneShift.y),alpha:new MotionValue(0)};const device=task.querySelector('.device');device.style.opacity='0';installPhoneDrag(device);task.querySelector('aside').style.opacity='0';}
 reviewView=new DescriptorView(task.querySelector('.device-content'),task.querySelector('aside'),{...snapshot.view,revision:snapshot.state.revision},{screenId:snapshot.state.screenId,onAction:(screenId,actionId,revision)=>session.act(screenId,actionId,revision),onNotice:tell,reduced:()=>reduced.matches});
}
function tick(now){const dt=document.hidden?0:Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;idleClock+=dt;session?.poll(now,{pauseResult:Boolean(dragGesture||phoneGesture)});if(phase!=='menu'&&session?.snapshot){const timer=document.querySelector('.timer'),state=session.snapshot.state;const seconds=Math.ceil(Math.max(0,state.deadlineAt===null?0:state.deadlineAt-(state.pausedAt??Date.now()))/1000);if(timer)timer.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
 if(['reveal','arrange','linking','ready','inserting','task','result','closing','finished'].includes(phase)){phaseElapsed+=dt;updateNodes(dt);}
 if(phase==='reveal'&&phaseElapsed>=(reduced.matches?.08:revealBurstDuration(nodeMotions.length))&&(reduced.matches||nodesSettled())){phase='arrange';phaseElapsed=0;document.querySelector('.palm-wrap').hidden=true;}
 if(phase==='arrange'&&phaseElapsed>=(reduced.matches?.08:REVEAL_TIMING.arrange)&&(reduced.matches||nodesSettled())){phase='linking';phaseElapsed=0;document.querySelector('.route').classList.add('linear','labels-visible');drawLinks(reduced.matches);}
 if(linkEntries.length&&['linking','ready','inserting','task','result','closing','finished'].includes(phase)){linkElapsed+=dt;updateLinks();}
 if(phase==='linking'&&linkElapsed>=(reduced.matches?.08:REVEAL_TIMING.trace+(linkEntries.length-1)*ROUTE_LINK_STAGGER)){phase='ready';openTask();}
 if(phase==='inserting'&&(reduced.matches||insertionSettled()))phase='task';
 if(phase==='task')phoneFiberElapsed+=dt;
 if(['inserting','task','result'].includes(phase))updatePhone(dt);
 if(channelView){channelView.device.inert=phase!=='task'||(wallMode&&phoneMotion.alpha.value<.85);channelView.tick(dt);}
 if(reviewView){reviewView.device.inert=phase!=='task'||(wallMode&&phoneMotion.alpha.value<.85);reviewView.tick(dt);}
 if(phase==='result'&&!dragGesture&&!phoneGesture&&phaseElapsed>=(reduced.matches?.12:.8)&&session.snapshot.state.status!=='result'){phase='closing';phaseElapsed=0;document.querySelector('.task').style.opacity='0';}
 if(phase==='closing'&&!dragGesture&&!phoneGesture&&phaseElapsed>=(reduced.matches?.05:.38)){const task=document.querySelector('.task');task.hidden=true;task.style.opacity='1';step=currentStep(session.snapshot);phoneMotion=null;phonePlan=null;phoneSide=null;phoneFiberElapsed=0;document.querySelector('.route').classList.remove('with-task');document.querySelectorAll('.node').forEach(b=>b.classList.toggle('current',Number(b.dataset.step)===step));drawLinks(true);phase='ready';openTask();}
 if(noticeUntil&&now>=noticeUntil){notice.classList.remove('visible');noticeUntil=0;}
 requestAnimationFrame(tick);
}
document.addEventListener('visibilitychange',()=>{session?.owner(!document.hidden);app.classList.toggle('paused',document.hidden);setGlowPaused(document.hidden);if(document.hidden){cancel(hold.owner);abortDrag();abortPhoneDrag();}});
window.addEventListener('pagehide',()=>{session?.close();clearGlowTiming();hold.cancel();abortDrag();abortPhoneDrag();});
function currentStep(snapshot){const index=snapshot.view.nodes.findIndex(node=>node.current);return index<0?snapshot.view.nodes.length-1:index-1;}
function refreshMissions(){missions=session.snapshot.view.missions.map(item=>{const visual=visualMissions.find(m=>m.id===item.missionId||m.id==='id'&&item.missionId==='digital-id');return {id:item.missionId,title:item.title,test:item.test,art:visual?.art??(['business','business-test'].includes(item.missionId)?'businessChannel':null),hasGaps:item.missing.length>0,steps:catalog.missions[item.missionId].taskIds.map(id=>catalog.tasks[id].title)};});}
function receiveSnapshot(snapshot){
 if(!mission||snapshot.state.missionId!==mission.id)return;
 if(snapshot.state.status==='expired'){menu();return;}
 if(phase==='palm'&&snapshot.state.scanned){reveal();return;}
 if(snapshot.state.status==='result'&&['task','inserting'].includes(phase)){const progress=snapshot.state.progress[mission.id];finishTask(progress.skipped.includes(renderedTaskId)?'skip':'complete');return;}
 if(phase==='ready'){step=currentStep(snapshot);document.querySelectorAll('.node').forEach(button=>button.classList.toggle('current',Number(button.dataset.step)===step));drawLinks(true);if(['completed','incomplete'].includes(snapshot.state.status))showFinal();else if(restoringResult&&snapshot.state.status==='task'){restoringResult=false;openTask();}}
 if(snapshot.state.status==='task'&&snapshot.state.taskId===renderedTaskId&&reviewView&&['task','inserting'].includes(phase)){renderedScreenId=snapshot.state.screenId;reviewView.update({...snapshot.view,revision:snapshot.state.revision},snapshot.state.screenId);}
}
async function boot(){
 const shared='../shared/src',[{MISSION_CATALOG},{createMissionSessionApplication},{createServerSessionPort}]=await Promise.all([import(`${shared}/content/mission-catalog.mjs`),import(`${shared}/application/mission-session.mjs`),import(`${shared}/application/server-session-port.mjs`)]);catalog=MISSION_CATALOG;
 const params=new URLSearchParams(location.search),profile=params.get('backend')??'local';if(!['local','server'].includes(profile))throw new Error('Неизвестный профиль backend');
 const port=profile==='local'?createMissionSessionApplication({catalog,persistence:createBrowserPersistence({storage:localStorage,key:`${SITE_SHARED_KEY}:${catalog.contentRevision}`})}):createServerSessionPort({getAuthHeaders:async()=>{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw new Error('STAND_AUTH_UNAVAILABLE');const state=await response.json();if(typeof state.csrf!=='string')throw new Error('STAND_AUTH_UNAVAILABLE');return {'X-VK-Token':state.csrf};}});
 session=createSiteSession({port,catalog,profile,sessionId:params.get('session')??'site-shared',onSnapshot:receiveSnapshot,onError:error=>tell(error.code==='INCORRECT_ANSWER'?'Попробуйте другой ответ.':`Backend: ${error.code??error.message}`)});
 const snapshot=await session.start();refreshMissions();if(snapshot.state.missionId)mountMission(snapshot);else renderMenu();requestAnimationFrame(tick);
}
boot().catch(error=>{app.replaceChildren();const message=document.createElement('p');message.style.padding='48px';message.textContent=`Не удалось открыть игровую сессию: ${error.code??error.message}. Прогресс сохранён; автоматической замены профиля нет.`;app.append(message);});
