import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {ICON_SHAPES} from '../../../max-game/src/journey-icons.mjs';
import {restoredCatalog} from './restored-content.mjs';

const dir=path.dirname(fileURLToPath(import.meta.url));
const {catalog,media}=await restoredCatalog();
const index=[];
for(const id of Object.keys(catalog.assets)){
  const asset=catalog.assets[id];
  const bytes=media[id].svg?Buffer.from(media[id].svg):Buffer.from(media[id].base64,'base64');
  const sha256=createHash('sha256').update(bytes).digest('hex');
  if(sha256!==asset.sha256)throw Error('Asset hash mismatch: '+id);
  index.push({assetId:id,path:asset.path,sha256,bytes:bytes.length});
}
const logo=await fs.readFile(path.resolve(dir,'../../BRANDS/MAX/assets/logos/max-symbol-color.svg'),'utf8');
const payload={catalog,shapes:ICON_SHAPES,logo};
const runtime=await fs.readFile(path.join(dir,'runtime.js'),'utf8');
await fs.writeFile(path.join(dir,'code.js'),'// Generated by build.mjs; edit runtime.js.\nconst PACK='+JSON.stringify(payload)+';\n'+runtime);
const ui=await fs.readFile(path.join(dir,'ui.template.html'),'utf8');
await fs.writeFile(path.join(dir,'ui.html'),ui.replace('/* EMBEDDED_MEDIA */',()=>JSON.stringify(media).replaceAll('<','\\u003c')));
await fs.writeFile(path.join(dir,'content-index.json'),JSON.stringify({revision:catalog.contentRevision,summary:catalog.summary,reviewSource:catalog.reviewSource,legacyCoverage:catalog.legacyCoverage,commentLedger:catalog.commentLedger,missions:Object.values(catalog.missions),tasks:catalog.tasks,assets:index},null,2)+'\n');
console.log(JSON.stringify({...catalog.summary,bytes:index.reduce((n,a)=>n+a.bytes,0)}));
